# Generated by Django 2.1.1 on 2018-09-24 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CheckClassroom',
            fields=[
                ('room_id', models.IntegerField(primary_key=True, serialize=False)),
                ('room_short_name', models.CharField(blank=True, max_length=64, null=True)),
                ('room_name', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'db_table': 'check_classroom',
            },
        ),
        migrations.CreateModel(
            name='CheckQuestion',
            fields=[
                ('check_id', models.IntegerField(primary_key=True, serialize=False)),
                ('equip_id', models.IntegerField(blank=True, null=True)),
                ('check_type', models.TextField(blank=True, null=True)),
                ('check_text', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'check_question',
            },
        ),
    ]
